# Generated by Django 4.1.2 on 2022-10-17 14:19

import checks.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("printers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Check",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("kitchen", "Kitchen"), ("client", "Client")],
                        max_length=7,
                        verbose_name="Check type",
                    ),
                ),
                ("order", models.JSONField(verbose_name="Order data")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("rendered", "Rendered"),
                            ("Printed", "Printed"),
                        ],
                        max_length=8,
                        verbose_name="Check status",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        upload_to=checks.models.generate_file_path,
                        verbose_name="File location",
                    ),
                ),
                (
                    "printer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="printers.printer",
                        verbose_name="Printer ID",
                    ),
                ),
            ],
            options={
                "ordering": ("-id",),
            },
        ),
    ]
