# Generated by Django 4.1.2 on 2022-10-17 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("printers", "0001_initial"),
        ("checks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="check",
            name="printer_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="printer",
                to="printers.printer",
                verbose_name="Printer ID",
            ),
        ),
    ]
