# Generated by Django 4.1.2 on 2022-10-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0002_alter_check_printer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="check",
            name="order",
            field=models.JSONField(blank=True, verbose_name="Order data"),
        ),
    ]
