# Generated by Django 4.1.2 on 2022-10-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0003_alter_check_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="check",
            name="order",
            field=models.JSONField(blank=True, null=True, verbose_name="Order data"),
        ),
    ]
