# Generated by Django 4.1.2 on 2022-10-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0004_alter_check_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="check",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("rendered", "Rendered"),
                    ("Printed", "Printed"),
                ],
                default="NEW",
                max_length=8,
                verbose_name="Check status",
            ),
        ),
    ]
