# Generated by Django 4.1.2 on 2022-10-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Printer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                (
                    "api_key",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="API key"
                    ),
                ),
                (
                    "check_type",
                    models.CharField(
                        choices=[("kitchen", "Kitchen"), ("client", "Client")],
                        max_length=7,
                        verbose_name="Check type",
                    ),
                ),
                ("point_id", models.IntegerField(verbose_name="Point ID")),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
